[workspace]
members = [
  "crates/weather",
  "crates/unsplash"
]

[package]
name = "fjordgard"
version = "0.1.0"
edition = "2024"

[dependencies]
fjordgard-weather = { version = "0.1.0", path = "crates/weather" }
tokio = { version = "1.45.1", features = ["full"] }
