[package]
name = "fjordgard-weather"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.20", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"

[dev-dependencies]
tokio = { version = "1.45.1", features = ["rt", "macros"] }
